Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FYP.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Security.Claims;

namespace FYP.Controllers
{
    public class CustomerController : Controller
    {

        [Authorize(Roles = "C")]
        [HttpGet]
        public IActionResult AllDetails()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string select = @"SELECT C.*, U.User_fullname, U.User_Password
                    FROM Customer C, Users U 
                    WHERE C.UserEmail = U.UserEmail
                     AND C.UserEmail = '{0}'";

            DataTable dt = DBUtl.GetTable(select, userid);

            if (dt.Rows.Count == 1)
            {
                return View("AllDetails", dt.Rows);
            }
            else
            {
                TempData["Message"] = "Customer Record does not exist";
                TempData["MsgType"] = "warning";
                return RedirectToAction("AllDetails");
            }
        }

        // Display customer personal information (for the logged in account) 
        [Authorize(Roles = "C")]
        public IActionResult CustIndex()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string sql = @"SELECT * FROM Customer WHERE userEmail = '{0}'";

            List<CustomerDetails> lstCust = DBUtl.GetList<CustomerDetails>(sql, userid);
            if (lstCust.Count == 1)
            {
                CustomerDetails cust = lstCust[0];
                return View("CustIndex", cust);
            }
            else
            {
                TempData["Message"] = "Customer Record does not exist";
                TempData["MsgType"] = "warning";
                return RedirectToAction("CustIndex");
            }
        }

        //Update Personal information
        [Authorize(Roles = "C")]
        public IActionResult CustUpdate(string id)
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string sql = @"SELECT * FROM Customer 
                         WHERE userEmail='{0}'";

            List<CustomerDetails> lstCust = DBUtl.GetList<CustomerDetails>(sql, userid);
            if (lstCust.Count == 1)
            {
                CustomerDetails cust = lstCust[0];
                return View(cust);
            }
            else
            {
                ViewData["Message"] = "Customer Record does not exist";
                ViewData["MsgType"] = "warning";
                return View("CustIndex");
            }
        }

        [Authorize(Roles = "C")]
        [HttpPost]
        public IActionResult CustUpdate(CustomerDetails cust)
        {

            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Invalid Input";
                ViewData["MsgType"] = "danger";
                return View("CustIndex", cust);
            }
            else
            {
                string sql = @"UPDATE Customer  
                              SET CustomerNo={1}, Date_of_birth='{2:yyyy-MM-dd}', Customer_Address='{3}'
                            WHERE UserEmail='{0}'";

                if (DBUtl.ExecSQL(sql, cust.UserEmail, cust.CustomerNo,
                    cust.Date_of_birth, cust.Customer_Address) == 1)

                {
                    ViewData["Message"] = "Personal Information Updated!";
                    ViewData["MsgType"] = "success";
                }
                else
                {
                    ViewData["Message"] = DBUtl.DB_Message;
                    ViewData["MsgType"] = "danger";

                    return View("CustUpdate");
                }

                return View("CustIndex");
            }
        }


        // UPDATE FULLNAME AND PASSWORD
        [Authorize(Roles = "C")]
        public IActionResult AccountDetail()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string sql = @"SELECT User_fullname, User_Password FROM Users WHERE userEmail = '{0}'";


            List<VisitorRegistration> lstCust = DBUtl.GetList<VisitorRegistration>(sql, userid);
            if (lstCust.Count == 1)
            {
                VisitorRegistration cust = lstCust[0];
                return View("AccountDetail", cust);
            }

            else
            {
                TempData["Message"] = "Customer Record does not exist";
                TempData["MsgType"] = "warning";
                return RedirectToAction("AccountDetail");
            }
        }


        [Authorize(Roles = "C")]
        public IActionResult AccountUpdate()
        {
            string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string sql = @"SELECT * FROM Users 
                         WHERE userEmail='{0}'";

            List<VisitorRegistration> lstCust = DBUtl.GetList<VisitorRegistration>(sql, userid);
            if (lstCust.Count == 1)
            {
                VisitorRegistration cust = lstCust[0];
                return View(cust);
            }
            else
            {
                ViewData["Message"] = "Account Record does not exist";
                ViewData["MsgType"] = "warning";
                return View("AccountDetail");
            }
        }

        [Authorize(Roles = "C")]
        [HttpPost]
        public IActionResult AccountUpdate(VisitorRegistration cust)
        {

            if (!ModelState.IsValid)
            {
                ViewData["Message"] = "Invalid";
                ViewData["MsgType"] = "danger";
                return View("AccountDetail", cust);
            }
            else
            {

                string sql = @"UPDATE Users  
                              SET User_fullname ='{1}', User_Password = '{2}', User_type ='C'
                            WHERE userEmail='{0}'";

                if (DBUtl.ExecSQL(sql, cust.UserEmail, cust.User_fullname, cust.User_Password, cust.User_type) == 1)

                {
                    ViewData["Message"] = "Account Details Updated!";
                    ViewData["MsgType"] = "success";

                    return View("AccountDetail");
                }
                else
                {
                    ViewData["Message"] = DBUtl.DB_Message;
                    ViewData["MsgType"] = "danger";

                    return View("AccountUpdate");
                }


            }

        }

        //List of orders made by specific customer
        [Authorize(Roles = "A,S")]
        public IActionResult CustOrderList(string id)
        {
            //string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            string select = String.Format(@"SELECT O.*, OD.Quantity, (OD.Quantity*O.Order_price) AS TotalPrice  
                FROM Orders O, Order_detail OD  
                WHERE OD.Order_id = O.Order_id
                AND O.UserEmail = '{0}'", id);

            DataTable dt = DBUtl.GetTable(select);
            return View("CustOrderList", dt.Rows);
        }

        //[Authorize(Roles = "C")]
        //[HttpPost]
        //public IActionResult StopLogin()
        //{
        //    string userid = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        //    string sql = String.Format(@"SELECT StopLogin FROM Users 
        //                 WHERE userEmail='{0}'", userid);

        //    if (sql.Equals("NULL"))
        //    {
        //        return View("test");
        //    }

        //    return View("StopLogin");
        //}

    }
}

Controllers/GraphController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data;
using FYP.Models;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace FYP.Controllers
{
    public class GraphController : Controller
    {

        //Customer with most orders made
        [Authorize(Roles = "A")]
        public IActionResult MostOrderMade()
        {
            string select = @"SELECT UserEmail, COUNT(Order_id) AS Order_id
                                     FROM Orders
                                        WHERE YEAR(Order_Date) = YEAR(getdate())
                                        AND MONTH(Order_Date) = MONTH(getdate())
                                      GROUP BY UserEmail
                                      ORDER BY 2 DESC";

            DataTable dt = DBUtl.GetTable(select);
            return View(dt.Rows);
        }

        //Customer with most spending amount
        [Authorize(Roles = "A")]
        public IActionResult MostSpendings()
        {
            string select = @"SELECT O.UserEmail, SUM(O.Order_price*OD.Quantity) AS Order_price
                                     FROM Orders O, Order_detail OD
WHERE O.Order_id = OD.Order_id
AND YEAR(Order_Date) = YEAR(getdate())
AND MONTH(Order_Date) = MONTH(getdate())
                                      GROUP BY UserEmail
                                      ORDER BY 2 DESC";

            DataTable dt = DBUtl.GetTable(select);
            return View(dt.Rows);
        }

        [Authorize(Roles = "A")]
        public IActionResult Sample()
        {
            return View();
        }

        [Authorize(Roles = "A")]
        public IActionResult SideDish()
        {
            return View();
        }

        [Authorize(Roles = "A")]
        public IActionResult SetMeal()
        {
            return View();
        }

    }
}

Views/Customer/AccountDetail.cshtml
@model VisitorRegistration

<div>
    <div class="col-sm-1 col-sm-6">
        <h2 style="margin-bottom:5px">
            <img style="border-radius:50% ;margin-bottom:40px" src="~/images/profile.png" width="100" height="100" />
            &nbsp;&nbsp;
            <b style="font-family:'Comic Sans MS'">Account Details</b>
        </h2>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-1" for="User_fullname">Name :</label>
        <div class="col-sm-4">
            <input type="text" asp-for="User_fullname" class="form-control" style="background-color:gainsboro" readonly />
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-1" for="User_Password">Password :</label>
        <div class="col-sm-4">
            <input type="text" value="Hidden" class="form-control" style="background-color:gainsboro; color:darkred" readonly />
        </div>
    </div>

    <input type="text" asp-for="User_Password" hidden />
    <input type="text" asp-for="UserEmail" hidden />
    <input type="text" asp-for="User_type" hidden />



    <div class="col-sm-6" style="margin-left:300px">
        <h5>
            @if (User.IsInRole("C"))
            {
                <a asp-controller="Customer" asp-action="AccountUpdate"><input type="submit" class="btn btn-warning fa" value="Edit Details" /></a>

            }
        </h5>
    </div>
    <br />
    <a asp-controller="Customer" asp-action="AllDetails"> <u>View All Details</u> </a>
</div>

@if (ViewData["Message"] != null)
{
    <div class="form-group row">
        <div class="col-sm-6">
            <div class="alert alert-@ViewData["MsgType"]">
                <text>@Html.Raw(ViewData["Message"])</text>
            </div>
        </div>
    </div>
}

Views/Customer/AccountUpdate.cshtml
@model VisitorRegistration


<form asp-controller="Customer"
      asp-action="AccountUpdate"
      method="post">

    <br />
    <div class="form-group row">
        <div class="col-sm-6">
            <h2><b>Update Account Detail</b></h2>
        </div>
    </div>

    <input type="text" asp-for="UserEmail" hidden />

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="User_fullname">Name :</label>
        <div class="col-sm-4">
            <input type="text" placeholder="Enter your fullname" asp-for="User_fullname" class="form-control" />
        </div>
        <div class="col-sm-3">
            <span asp-validation-for="User_fullname" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="User_Password">New or current Password :</label>
        <div class="col-sm-4">
            <input type="password" placeholder="Enter New or current Password" asp-for="User_Password" class="form-control" />
        </div>
        <div class="col-sm-3">
            <span asp-validation-for="User_Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="User_Password2">Re-enter Password :</label>
        <div class="col-sm-4">
            <input type="password" placeholder="Re-enter your Password to confirm" asp-for="User_Password2" class="form-control" />
        </div>
        <div class="col-sm-3">
            <span asp-validation-for="User_Password2" class="text-danger"></span>
        </div>
    </div>





    <div class="form-group row">
        <div class="offset-sm-2 col-sm-6">
            <a asp-controller="Customer" asp-action="AccountUpdate"
               onclick='return confirm("Are you sure you want to save changes ?")'>
                <input type="submit" value="Save" class="btn btn-primary" />
            </a>
        </div>
    </div>

    <h5><a href="AccountDetail">Back</a></h5>



    @if (ViewData["Message"] != null)
    {
        <div class="form-group row">
            <div class="col-sm-6">
                <div class="alert alert-@ViewData["MsgType"]">
                    <text>@Html.Raw(ViewData["Message"])</text>
                </div>
            </div>
        </div>
    }

</form>

Views/Customer/AllDetails.cshtml
@using System.Data
@model DataRowCollection

@foreach (DataRow cust in Model)
{

    <br />
        <div class="offset-sm-1 col-sm-4" style="font-family:'Comic Sans MS'">
            <h2>
                @*<img src="~/images/profile.png" width="100" height="100" />*@
                <b><u>ALL DETAILS</u></b>
            </h2>
        </div>
        <br />

        <div style="display:compact;">
            <h5><b>Account Details</b></h5>

            <br />
            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["User_fullname"]">Name :</label>
                <div class="col-sm-4">
                    <input type="text" asp-for="@cust["User_fullname"]" class="form-control" style="background-color:gainsboro" readonly />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["User_Password"]">Password :</label>
                <div class="col-sm-4">
                    <input type="text" value="Hidden" class="form-control" style="background-color:gainsboro; color:darkred" readonly />
                </div>
            </div>
            <input type="text" asp-for="@cust["User_Password"]" hidden />

            <h5>
                <a asp-controller="Customer" asp-action="AccountDetail"><input type="button" class="btn btn-basic" value="Edit Account Details" /></a>

            </h5>
            <hr />

            <h5><b>Personal Information</b></h5>
            <br />
            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["UserEmail"]">E-mail :</label>
                <div class="col-sm-4">
                    <input type="text" asp-for="@cust["UserEmail"]" class="form-control" style="background-color:gainsboro" readonly />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["CustomerNo"]">Phone Number :</label>
                <div class="col-sm-4">
                    <input type="text" asp-for="@cust["CustomerNo"]" class="form-control" style="background-color:gainsboro" readonly />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["Date_of_birth"]">BirthDate :</label>
                <div class="col-sm-4">
                    <input type="text" asp-for="@cust["Date_of_birth"]" asp-format="{0:dd MMM yyyy}" class="form-control" style="background-color:gainsboro" readonly />
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-2" for="@cust["Customer_Address"]">Address :</label>
                <div class="col-sm-4">
                    <input type="text" asp-for="@cust["Customer_Address"]" class="form-control" style="background-color:gainsboro" readonly />
                </div>
            </div>

            <h5>
                <a asp-controller="Customer" asp-action="CustIndex"><input type="button" class="btn btn-basic" value="Edit Personal Information" /></a>

            </h5>
            <br />
        </div>
        
}
@if (ViewData["Message"] != null)
{
    <div class="form-group row">
        <div class="offset-sm-2 col-sm-6">
            <div class="alert alert-@ViewData["MsgType"]">
                <text>@Html.Raw(ViewData["Message"])</text>
            </div>
        </div>
    </div>
}

Views/Customer/CustIndex.cshtml
@model CustomerDetails

<div style="justify-content:center">
    <div class="col-sm-1 col-sm-6">
        <h2 style="margin-bottom:5px">
            <img style="border-radius:50% ;margin-bottom:40px" src="~/images/profile.png" width="100" height="100" />
            &nbsp;&nbsp;
            <b style="font-family:'Comic Sans MS'">Personal Information</b>
        </h2>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" for="Userid">E-mail :</label>
        <div class="col-sm-4">
            <input type="text" asp-for="UserEmail" class="form-control" style="background-color:gainsboro" readonly />
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" for="CustomerNo">Phone Number :</label>
        <div class="col-sm-4">
            <input type="text" asp-for="CustomerNo" class="form-control" style="background-color:gainsboro" readonly />
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" for="Date_of_birth">BirthDate :</label>
        <div class="col-sm-4">
            <input type="text" asp-for="Date_of_birth" asp-format="{0:yyyy-MM-dd}" class="form-control" style="background-color:gainsboro" readonly />
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" for="Customer_Address">Address :</label>
        <div class="col-sm-4">
            <input type="text" asp-for="Customer_Address" class="form-control" style="background-color:gainsboro" readonly />
        </div>
    </div>


    <div class="offset-sm-4 col-sm-6">
        <h5>
            @if (User.IsInRole("C"))
            {
                <a asp-controller="Customer" asp-action="CustUpdate"><input type="submit" class="btn btn-warning fa" value="Edit Information" /></a>

            }
        </h5>
    </div>
    <br />
    <a asp-controller="Customer" asp-action="AllDetails"> <u>View All Details</u> </a>
</div>

@if (ViewData["Message"] != null)
{
    <div class="form-group row">
        <div class="col-sm-6">
            <div class="alert alert-@ViewData["MsgType"]">
                <text>@Html.Raw(ViewData["Message"])</text>
            </div>
        </div>
    </div>
}

Views/Customer/CustOrderList.cshtml
<!--TABLE THAT SHOWS ALL ORDERS MADE BY THAT SPECIFIC CUSTOMER-->
@using System.Data;
@model DataRowCollection

@section MoreScripts {
    <link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#jsOrderTable').DataTable({
                ordering: true,
                paging: true,
                searching: true,
                info: true,
                lengthChange: false

            });
        });
    </script>


}

    <form asp-controller="Graph"
          asp-action="CustOrderList"
          method="post">

            <br />
            <div style="text-align:center">
                <h2><b>All orders made by customer</b></h2>

            </div>
            <hr />

 
        @if (TempData["Message"] != null)
        {
            <div class="alert alert-@TempData["MsgType"]">
                @TempData["Message"]
            </div>
        }
        <table id="jsOrderTable" class="table table-condensed table-hover table-bordered" style="border:double">

            <thead style="text-align:center">

                <tr style="background-color:navajowhite">

                    <th scope="col">Customer's Email</th>
                    <th scope="col">Order ID</th>
                    <th scope="col">Order Date</th>
                    <th scope="col">Order Time</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>


            <tbody style="text-align:center;">
                @foreach (DataRow ord in Model)
                {
                <tr>
                    <td>@ord["UserEmail"]</td>
                    <td>@ord["Order_id"]</td>
                    <td>@String.Format("{0:dd MMM yyyy}", ord["Order_Date"])</td>
                    <td>@String.Format("{0:hh:mm tt}", ord["Order_Time"])</td>
                    <td>@ord["Quantity"]</td>
                    <td>@String.Format("{0:C}", ord["Order_price"])</td>
                    <td>@String.Format("{0:C}", ord["TotalPrice"])</td>
                    <td align="center">
                        @if (ord["Order_Status"].Equals("Delivered"))
                        {
                            <b style="color:red">@ord["Order_Status"]  </b>
                            <b><i style="color:red" class="fa fa-check"></i></b>
                        }
                        else
                        {
                            <b style="color:green">@ord["Order_Status"]</b>
                        }

                    </td>

                </tr>
                }
            </tbody>
        </table>
    </form>
<br />

Views/Customer/CustUpdate.cshtml
@model CustomerDetails ;


<form asp-controller="Customer"
      asp-action="CustUpdate"
      method="post">

    <br />
    <div class="form-group row">
        <div class="col-sm-6">
            <h2><b>Update Personal Details</b></h2>
        </div>
    </div>


    <input type="text" asp-for="UserEmail" hidden />

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="CustomerNo">Phone Number :</label>
        <div class="col-sm-4">
            <input type="text" placeholder="Phone Number" asp-for="CustomerNo" class="form-control" />
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="CustomerNo" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="Date_of_birth">Birthdate :</label>
        <div class="col-sm-4">
            <input type="text" placeholder="Birthdate (YYYY-MM-DD)" asp-for="Date_of_birth" asp-format="{0:yyyy-MM-dd}" class="form-control" />
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="Date_of_birth" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="control-label col-sm-2" asp-for="Customer_Address">Address :</label>
        <div class="col-sm-4">
            <input type="text" placeholder="Address" asp-for="Customer_Address" class="form-control" />
        </div>
        <div class="col-sm-4">
            <span asp-validation-for="Customer_Address" class="text-danger"></span>
        </div>
    </div>




    <div class="form-group row">
        <div class="offset-sm-2 col-sm-6">
            <a asp-controller="Customer" asp-action="CustUpdate"
               onclick='return confirm("Are you sure you want to save changes ?")'>
                <input type="submit" value="Save" class="btn btn-primary" />
            </a>
        </div>
    </div>

    <h5><a href="CustIndex">Back</a></h5>



    @if (ViewData["Message"] != null)
    {
        <div class="form-group row">
            <div class="offset-sm-2 col-sm-6">
                <div class="alert alert-@ViewData["MsgType"]">
                    <text>@Html.Raw(ViewData["Message"])</text>
                </div>
            </div>
        </div>
    }

</form>